Repository dusk-network/wallet-core, pull requests merged in 2022-01, with the labels that each got.

#5 Release `0.1.0` preparation
  .github/workflows/dusk_ci.yml
  CHANGELOG.md
  Cargo.toml
  src/ffi.rs
  src/lib.rs
  src/tx.rs
  tests/mock.rs
  tests/wallet.rs
Labels: area:wallet, mark:testnet, team:Core

#10 Add compute_proof_and_propagate
  src/ffi.rs
  src/imp.rs
  src/lib.rs
  src/tx.rs
  tests/mock.rs
  tests/wallet.rs
Labels: area:architecture, mark:testnet

#23 Change stake keys to BLS
  Cargo.toml
  src/ffi.rs
  src/imp.rs
  src/lib.rs
  tests/mock.rs
  tests/wallet.rs
Labels: area:wallet, team:Core

#30 Update state service to take APK
  Cargo.toml
  src/ffi.rs
  src/imp.rs
  src/lib.rs
  tests/mock.rs
Labels: mark:testnet, team:Core

#32 Fix `Canon` encoding of `Transaction`
  Cargo.toml
  src/tx.rs
  tests/mock.rs
  tests/wallet.rs
Labels: area:wallet, mark:testnet, team:Core

#35 Update STCT to use `dusk-schnorr::Signature`
  Cargo.toml
  src/ffi.rs
  src/imp.rs
  src/lib.rs
  tests/mock.rs
Labels: mark:testnet, team:Core

#38 Update tx to generate change output
  Cargo.toml
  src/imp.rs
Labels: mark:testnet, team:Core
